name: student_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  email_validator: ^3.0.0
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  flutter_automation: ^2.0.0

  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon.jpg  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-regular.ttf
        - asset: assets/fonts/inter-bold.ttf
          weight: 700


